namespace: default
appName: adminx
version: 0.0.1
development: true
log:
  withTraceID: true
  traceIDKey: "traceId"
  cores:
    - level: debug
      outputPaths:
        - stdout
  rotate:
    localtime: true
# use open telemetry
#otel:
#  traceExporter: otlp
#  otlp:
#    endpoint: "127.0.0.1:4317"
#    client:
#      dialOption:
#        - timeout: 5s
authz:
  autoSave: true
  watcherOptions:
    options:
      addr: "127.0.0.1:6379"
      channel: "/casbin"
  model: "etc/rbac_model.conf"

jwt: &jwt
  signingMethod: "HS256"
  signingKey: "secret"

web:
  server:
    addr: :8080
  engine:
    routerGroups:
      - default:
          middlewares:
            - cors:
                allowOrigins: ['*']
                allowHeaders: ["*"]
            - accessLog:
                exclude:
                  - IntrospectionQuery
            - recovery:
            - errorHandle:
            - gzip:
      - graphql:
          basePath: "/graphql"
          middlewares:
            - graphql:
                group: "/graphql"
                withAuthorization: false
                appCode: "resource"
                middlewares:
                  operation:
                    - tenant:
                    - jwt: *jwt
                    - tokenSign: # 利用IDE开发时,可注释
                header: ## dev mode, remove in production, set the value in your .env.local
                  X-Tenant-ID: ${TENANT}
                  Authorization: "${AUTHORIZATION}"

store:
  portal:
    driverName: mysql
    dsn: "root:@tcp(localhost:3306)/portal?parseTime=true&loc=Local"
  redis: &redis
    addrs:
      - 127.0.0.1:6379
    db: 1

cache:
  redis:
    driverName: redis
    <<: *redis
    local:
      size: 1000
      ttl: 100s

entcache:
  hashQueryTTL: 5s

oas:
  files:
    prefixDir: "/resource"  # 相对于存储服务的前缀路径
    baseUrl: "http://127.0.0.1:10071"
  msgsrv:
    baseUrl: "http://127.0.0.1:10072"

kosdk:
  client:
    timeout: 2s
    oauth2:
      clientID: 206734260394752
      clientSecret: T2UlqISVFq4DR9InXamj3l74iWdu3Tyr
      endpoint:
        tokenURL: http://127.0.0.1:10070/token
      scopes:
      storeKey: redis
  signer:
    authScheme: "KO-HMAC-SHA1"
    authHeaders: [ "timestamp", "nonce" ]
    signedLookups:
      accessToken: "header:authorization>bearer"
      timestamp:
      nonce:
      url: CanonicalUri
    nonceLen: 12
  plugin:
    msg:
      baseUrl: "http://127.0.0.1:10072"
    file:
      baseUrl: "http://127.0.0.1:10071"