// Code generated by ent, DO NOT EDIT.

package quotaitem

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/woocoos/knockout/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldLTE(FieldID, id))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v int) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldEQ(FieldCode, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldEQ(FieldDescription, v))
}

// Unit applies equality check predicate on the "unit" field. It's identical to UnitEQ.
func Unit(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldEQ(FieldUnit, v))
}

// Active applies equality check predicate on the "active" field. It's identical to ActiveEQ.
func Active(v bool) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldEQ(FieldActive, v))
}

// DefaultLimit applies equality check predicate on the "default_limit" field. It's identical to DefaultLimitEQ.
func DefaultLimit(v int64) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldEQ(FieldDefaultLimit, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v int) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v int) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...int) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...int) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v int) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v int) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v int) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v int) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldNotNull(FieldUpdatedAt))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldContainsFold(FieldCode, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldContainsFold(FieldDescription, v))
}

// ResourceTypeEQ applies the EQ predicate on the "resource_type" field.
func ResourceTypeEQ(v ResourceType) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldEQ(FieldResourceType, v))
}

// ResourceTypeNEQ applies the NEQ predicate on the "resource_type" field.
func ResourceTypeNEQ(v ResourceType) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldNEQ(FieldResourceType, v))
}

// ResourceTypeIn applies the In predicate on the "resource_type" field.
func ResourceTypeIn(vs ...ResourceType) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldIn(FieldResourceType, vs...))
}

// ResourceTypeNotIn applies the NotIn predicate on the "resource_type" field.
func ResourceTypeNotIn(vs ...ResourceType) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldNotIn(FieldResourceType, vs...))
}

// UnitEQ applies the EQ predicate on the "unit" field.
func UnitEQ(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldEQ(FieldUnit, v))
}

// UnitNEQ applies the NEQ predicate on the "unit" field.
func UnitNEQ(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldNEQ(FieldUnit, v))
}

// UnitIn applies the In predicate on the "unit" field.
func UnitIn(vs ...string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldIn(FieldUnit, vs...))
}

// UnitNotIn applies the NotIn predicate on the "unit" field.
func UnitNotIn(vs ...string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldNotIn(FieldUnit, vs...))
}

// UnitGT applies the GT predicate on the "unit" field.
func UnitGT(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldGT(FieldUnit, v))
}

// UnitGTE applies the GTE predicate on the "unit" field.
func UnitGTE(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldGTE(FieldUnit, v))
}

// UnitLT applies the LT predicate on the "unit" field.
func UnitLT(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldLT(FieldUnit, v))
}

// UnitLTE applies the LTE predicate on the "unit" field.
func UnitLTE(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldLTE(FieldUnit, v))
}

// UnitContains applies the Contains predicate on the "unit" field.
func UnitContains(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldContains(FieldUnit, v))
}

// UnitHasPrefix applies the HasPrefix predicate on the "unit" field.
func UnitHasPrefix(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldHasPrefix(FieldUnit, v))
}

// UnitHasSuffix applies the HasSuffix predicate on the "unit" field.
func UnitHasSuffix(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldHasSuffix(FieldUnit, v))
}

// UnitIsNil applies the IsNil predicate on the "unit" field.
func UnitIsNil() predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldIsNull(FieldUnit))
}

// UnitNotNil applies the NotNil predicate on the "unit" field.
func UnitNotNil() predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldNotNull(FieldUnit))
}

// UnitEqualFold applies the EqualFold predicate on the "unit" field.
func UnitEqualFold(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldEqualFold(FieldUnit, v))
}

// UnitContainsFold applies the ContainsFold predicate on the "unit" field.
func UnitContainsFold(v string) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldContainsFold(FieldUnit, v))
}

// ActiveEQ applies the EQ predicate on the "active" field.
func ActiveEQ(v bool) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldEQ(FieldActive, v))
}

// ActiveNEQ applies the NEQ predicate on the "active" field.
func ActiveNEQ(v bool) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldNEQ(FieldActive, v))
}

// DefaultLimitEQ applies the EQ predicate on the "default_limit" field.
func DefaultLimitEQ(v int64) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldEQ(FieldDefaultLimit, v))
}

// DefaultLimitNEQ applies the NEQ predicate on the "default_limit" field.
func DefaultLimitNEQ(v int64) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldNEQ(FieldDefaultLimit, v))
}

// DefaultLimitIn applies the In predicate on the "default_limit" field.
func DefaultLimitIn(vs ...int64) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldIn(FieldDefaultLimit, vs...))
}

// DefaultLimitNotIn applies the NotIn predicate on the "default_limit" field.
func DefaultLimitNotIn(vs ...int64) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldNotIn(FieldDefaultLimit, vs...))
}

// DefaultLimitGT applies the GT predicate on the "default_limit" field.
func DefaultLimitGT(v int64) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldGT(FieldDefaultLimit, v))
}

// DefaultLimitGTE applies the GTE predicate on the "default_limit" field.
func DefaultLimitGTE(v int64) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldGTE(FieldDefaultLimit, v))
}

// DefaultLimitLT applies the LT predicate on the "default_limit" field.
func DefaultLimitLT(v int64) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldLT(FieldDefaultLimit, v))
}

// DefaultLimitLTE applies the LTE predicate on the "default_limit" field.
func DefaultLimitLTE(v int64) predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldLTE(FieldDefaultLimit, v))
}

// DefaultLimitIsNil applies the IsNil predicate on the "default_limit" field.
func DefaultLimitIsNil() predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldIsNull(FieldDefaultLimit))
}

// DefaultLimitNotNil applies the NotNil predicate on the "default_limit" field.
func DefaultLimitNotNil() predicate.QuotaItem {
	return predicate.QuotaItem(sql.FieldNotNull(FieldDefaultLimit))
}

// HasQuota applies the HasEdge predicate on the "quota" edge.
func HasQuota() predicate.QuotaItem {
	return predicate.QuotaItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, QuotaTable, QuotaColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasQuotaWith applies the HasEdge predicate on the "quota" edge with a given conditions (other predicates).
func HasQuotaWith(preds ...predicate.Quota) predicate.QuotaItem {
	return predicate.QuotaItem(func(s *sql.Selector) {
		step := newQuotaStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.QuotaItem) predicate.QuotaItem {
	return predicate.QuotaItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.QuotaItem) predicate.QuotaItem {
	return predicate.QuotaItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.QuotaItem) predicate.QuotaItem {
	return predicate.QuotaItem(sql.NotPredicates(p))
}
