target: "./api/oas"
models:
  UUID:
    model: github.com/google/uuid.UUID
  '#/components/schemas/ApiResponse':
    model: github.com/tsingsun/woocoo/cmd/woco/oasgen/internal/integration/extra.ApiResponse