namespace: default
appName: auth
version: 0.0.1
development: true
# use open telemetry
#otel:
#  traceExporter: otlp
#  otlp:
#    endpoint: "127.0.0.1:4317"
#    client:
#      dialOption:
#        - timeout: 5s
authz:
  watcherOptions:
    options:
      addr: "127.0.0.1:6379"
      channel: "/casbin"
  model: "etc/rbac_model.conf"

auth:
  captchaTimes: 3 # if login fail times, captcha will force show
  captchaTTL: 1m # captcha ttl
  loginFailTimes: 10 # login fail times will lock account
  loginFailLockTime: 10m # login fail lock time
  stateTokenTTL: 20m
  stateTokenSecret: "secret"
  jwt: &jwt
    signingMethod: "HS256"
    signingKey: "secret"
    tokenTTL: 1h
    refreshTokenTTL: 7d

web:
  server:
    addr: 127.0.0.1:10070
  engine:
    contextWithFallback: true
    routerGroups:
      - default:
          middlewares:
            - accessLog:
            - recovery:
            - errorHandle:
            - jwt:
                tokenStoreKey: redis
                exclude:
                  - "/login/auth"
                  - "/login/mfaqr.png"
                  - "/login/verify-factor"
                  - "/login/reset-password"
                  - "/captcha"
                <<: *jwt

grpc:
  server:
    addr: 127.0.0.1:10080
    engine:
      - unaryInterceptors:
          - accessLog:
          - recovery:
  #  registry:
  #    scheme: polaris
  #    ttl: 10s
  #    polaris:
  #      global:
  #        serverConnector:
  #          addresses:
  #            - 127.0.0.1:8091


store:
  portal:
    driverName: mysql
    dsn: "root:@tcp(localhost:3306)/portal?parseTime=true&loc=Local"
  redis: &redis
    type: standalone
    addr: 127.0.0.1:6379
    db: 1


cache:
  redis:
    <<: *redis
    local:
      size: 1000
      ttl: 100s

entcache:
  level: context
#  ttl: 5m # level: db时有效