input EnableDirectoryInput {
    """域名"""
    domain: String!
    name: String!
}

extend input CreateUserInput {
    loginProfile: CreateUserLoginProfileInput
    """如指定密码则填入,否则由系统自动生成密码"""
    password: CreateUserPasswordInput
    """地址信息"""
    contact: CreateUserAddrInput
}

input AssignRoleUserInput {
    """授权类型为角色或用户组的ID"""
    orgRoleID: ID!
    userID: ID!
    """生效开始时间"""
    startAt: Time
    """生效结束时间"""
    endAt: Time
}

"""树操作类型"""
enum TreeAction {
    """作为子节点"""
    child
    """上移"""
    up
    """下移"""
    down
}

"""列表操作类型"""
enum ListAction {
    """上移"""
    up
    """下移"""
    down
}

enum PolicyEffect {
    allow
    deny
}
type PolicyRule {
    effect: PolicyEffect!
    actions: [String!]
    resources: [String!]
    conditions: [String!]
}

input PolicyRuleInput {
    effect: PolicyEffect!
    actions: [String!]
    resources: [String!]
    conditions: [String!]
}

input GrantInput {
    principal: GID!
    orgScope: ID!
    policyID: ID!
}

type Mfa{
    secret: String!
    account: String!
}

extend type Org {
    """获取顶级组织"""
    TopOrg: Org
}

extend type OrgRole {
    """是否系统角色"""
    isAppRole: Boolean!
}

extend type OrgPolicy {
    """是否授权role"""
    isGrantRole(roleID:ID!): Boolean!
    """是否授权user"""
    isGrantUser(userID:ID!): Boolean!
}

extend type User {
    """是否分配role"""
    isAssignOrgRole(orgRoleID:ID!): Boolean!
    """是否允许解除角色授权"""
    isAllowRevokeRole(orgRoleID:ID!):Boolean!
    """地址信息"""
    contact: UserAddr
    """组织用户类型"""
    orgUserType(orgID:ID!): OrgUserUserType!
}

extend type Org {
    """是否允许解除应用策略"""
    isAllowRevokeAppPolicy(appPolicyID:ID!):Boolean!
    """组织的domain，如果没有设置，则会取最近的父组织的domain"""
    actualDomain: String!
}

extend type OrgRole {
    """是否分配给user"""
    isGrantUser(userID:ID!): Boolean!
}

extend type AppPolicy {
    """是否授权role"""
    isGrantAppRole(appRoleID:ID!): Boolean!
}

extend type Permission {
    """是否允许撤销：根用户授权及系统角色授权不允许撤销"""
    isAllowRevoke:Boolean!
}

input OrgUserPreferenceInput {
    """用户收藏菜单"""
    menuFavorite: [ID!]
    """用户最近访问菜单"""
    menuRecent: [ID!]
    """客户端偏好设置"""
    clientPreference: ClientPreferenceInput
}

"""业务调用的fileIdentity"""
type OrgFileIdentity {
    id: ID!
    createdBy: Int!
    createdAt: Time!
    updatedBy: Int
    updatedAt: Time
    """
    组织ID
    """
    tenantID: ID!
    """
    文件来源ID
    """
    fileSourceID: ID!
    """
    租户默认的凭证
    """
    isDefault: Boolean!
    """
    备注
    """
    comments: String
    source: FileSource!
}

"""内部调用fileIdentity"""
type FileIdentityForApp implements Node{
    id: ID!
    tenantID: ID!
    accessKeyID: String!
    accessKeySecret: String!
    """
    角色的资源名称(ARN)，用于STS
    """
    roleArn: String!
    """
    指定返回的STS令牌的权限的策略
    """
    policy: String
    """
    STS令牌的有效期，默认3600s
    """
    durationSeconds: Int
    """
    租户默认的凭证
    """
    isDefault: Boolean!
    source: FileSource!
}

type OrgLogo {
    logo: String
    thumbLogo: String
    favicon: String
}

input OrgLogoInput {
    logo: String
    thumbLogo: String
    favicon: String
}
type AppPolicyViewOrgPolicy{
    orgPolicy: OrgPolicy
    appPolicyView: AppPolicyView
}
"""查看用户mfa信息"""
type UserMfaInfo {
    """是否启用mfa"""
    mfaEnabled: Boolean!
    """秘钥"""
    secret: String!
    """二维码"""
    qrCodeUri: String!
    """用户账号"""
    accountName: String!
}

extend type OrgUserPreference {
    clientPreference(appCode: String!): ClientPreference!
}

type ClientPreference {
    appCode: String!
    values: [ClientPreferenceValue!]
}

type ClientPreferenceValue {
    key: String!
    value: String
    extension: String
}

input ClientPreferenceInput {
    """应用编码"""
    appCode: String!
    """应用偏好设置数据"""
    values: [ClientPreferenceValueInput!]
}

input ClientPreferenceValueInput {
    """根据业务场景定义key，存储时根据key更新"""
    key: String!
    """业务场景对应的值"""
    value: String
    """扩展字段，根据业务场景需求使用"""
    extension: String
}

extend type AppDict {
    """根据组织获取字典项,过滤有orgID与无orgID重复的code"""
    orgItems(
        """是否取消code过滤，不传会过滤重复的code"""
        noFilterCode: Boolean
    ): [AppDictItem!]!
}