// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/woocoos/knockout-go/ent/schemax/typex"
	"github.com/woocoos/knockout/ent/currency"
)

// CurrencyCreate is the builder for creating a Currency entity.
type CurrencyCreate struct {
	config
	mutation *CurrencyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedBy sets the "created_by" field.
func (_c *CurrencyCreate) SetCreatedBy(v int) *CurrencyCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CurrencyCreate) SetCreatedAt(v time.Time) *CurrencyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CurrencyCreate) SetNillableCreatedAt(v *time.Time) *CurrencyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *CurrencyCreate) SetUpdatedBy(v int) *CurrencyCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *CurrencyCreate) SetNillableUpdatedBy(v *int) *CurrencyCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CurrencyCreate) SetUpdatedAt(v time.Time) *CurrencyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CurrencyCreate) SetNillableUpdatedAt(v *time.Time) *CurrencyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCode sets the "code" field.
func (_c *CurrencyCreate) SetCode(v string) *CurrencyCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetName sets the "name" field.
func (_c *CurrencyCreate) SetName(v string) *CurrencyCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSign sets the "sign" field.
func (_c *CurrencyCreate) SetSign(v string) *CurrencyCreate {
	_c.mutation.SetSign(v)
	return _c
}

// SetNillableSign sets the "sign" field if the given value is not nil.
func (_c *CurrencyCreate) SetNillableSign(v *string) *CurrencyCreate {
	if v != nil {
		_c.SetSign(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *CurrencyCreate) SetStatus(v typex.SimpleStatus) *CurrencyCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CurrencyCreate) SetNillableStatus(v *typex.SimpleStatus) *CurrencyCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CurrencyCreate) SetID(v int) *CurrencyCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the CurrencyMutation object of the builder.
func (_c *CurrencyCreate) Mutation() *CurrencyMutation {
	return _c.mutation
}

// Save creates the Currency in the database.
func (_c *CurrencyCreate) Save(ctx context.Context) (*Currency, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CurrencyCreate) SaveX(ctx context.Context) *Currency {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CurrencyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CurrencyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CurrencyCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if currency.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized currency.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := currency.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := currency.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *CurrencyCreate) check() error {
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "Currency.created_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Currency.created_at"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Currency.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := currency.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Currency.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Currency.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := currency.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Currency.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Sign(); ok {
		if err := currency.SignValidator(v); err != nil {
			return &ValidationError{Name: "sign", err: fmt.Errorf(`ent: validator failed for field "Currency.sign": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Currency.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := currency.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Currency.status": %w`, err)}
		}
	}
	return nil
}

func (_c *CurrencyCreate) sqlSave(ctx context.Context) (*Currency, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CurrencyCreate) createSpec() (*Currency, *sqlgraph.CreateSpec) {
	var (
		_node = &Currency{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(currency.Table, sqlgraph.NewFieldSpec(currency.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(currency.FieldCreatedBy, field.TypeInt, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(currency.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(currency.FieldUpdatedBy, field.TypeInt, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(currency.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(currency.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(currency.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Sign(); ok {
		_spec.SetField(currency.FieldSign, field.TypeString, value)
		_node.Sign = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(currency.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Currency.Create().
//		SetCreatedBy(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CurrencyUpsert) {
//			SetCreatedBy(v+v).
//		}).
//		Exec(ctx)
func (_c *CurrencyCreate) OnConflict(opts ...sql.ConflictOption) *CurrencyUpsertOne {
	_c.conflict = opts
	return &CurrencyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Currency.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CurrencyCreate) OnConflictColumns(columns ...string) *CurrencyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CurrencyUpsertOne{
		create: _c,
	}
}

type (
	// CurrencyUpsertOne is the builder for "upsert"-ing
	//  one Currency node.
	CurrencyUpsertOne struct {
		create *CurrencyCreate
	}

	// CurrencyUpsert is the "OnConflict" setter.
	CurrencyUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedBy sets the "updated_by" field.
func (u *CurrencyUpsert) SetUpdatedBy(v int) *CurrencyUpsert {
	u.Set(currency.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *CurrencyUpsert) UpdateUpdatedBy() *CurrencyUpsert {
	u.SetExcluded(currency.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *CurrencyUpsert) AddUpdatedBy(v int) *CurrencyUpsert {
	u.Add(currency.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *CurrencyUpsert) ClearUpdatedBy() *CurrencyUpsert {
	u.SetNull(currency.FieldUpdatedBy)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CurrencyUpsert) SetUpdatedAt(v time.Time) *CurrencyUpsert {
	u.Set(currency.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CurrencyUpsert) UpdateUpdatedAt() *CurrencyUpsert {
	u.SetExcluded(currency.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *CurrencyUpsert) ClearUpdatedAt() *CurrencyUpsert {
	u.SetNull(currency.FieldUpdatedAt)
	return u
}

// SetCode sets the "code" field.
func (u *CurrencyUpsert) SetCode(v string) *CurrencyUpsert {
	u.Set(currency.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *CurrencyUpsert) UpdateCode() *CurrencyUpsert {
	u.SetExcluded(currency.FieldCode)
	return u
}

// SetName sets the "name" field.
func (u *CurrencyUpsert) SetName(v string) *CurrencyUpsert {
	u.Set(currency.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CurrencyUpsert) UpdateName() *CurrencyUpsert {
	u.SetExcluded(currency.FieldName)
	return u
}

// SetSign sets the "sign" field.
func (u *CurrencyUpsert) SetSign(v string) *CurrencyUpsert {
	u.Set(currency.FieldSign, v)
	return u
}

// UpdateSign sets the "sign" field to the value that was provided on create.
func (u *CurrencyUpsert) UpdateSign() *CurrencyUpsert {
	u.SetExcluded(currency.FieldSign)
	return u
}

// ClearSign clears the value of the "sign" field.
func (u *CurrencyUpsert) ClearSign() *CurrencyUpsert {
	u.SetNull(currency.FieldSign)
	return u
}

// SetStatus sets the "status" field.
func (u *CurrencyUpsert) SetStatus(v typex.SimpleStatus) *CurrencyUpsert {
	u.Set(currency.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CurrencyUpsert) UpdateStatus() *CurrencyUpsert {
	u.SetExcluded(currency.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Currency.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(currency.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CurrencyUpsertOne) UpdateNewValues() *CurrencyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(currency.FieldID)
		}
		if _, exists := u.create.mutation.CreatedBy(); exists {
			s.SetIgnore(currency.FieldCreatedBy)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(currency.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Currency.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CurrencyUpsertOne) Ignore() *CurrencyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CurrencyUpsertOne) DoNothing() *CurrencyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CurrencyCreate.OnConflict
// documentation for more info.
func (u *CurrencyUpsertOne) Update(set func(*CurrencyUpsert)) *CurrencyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CurrencyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *CurrencyUpsertOne) SetUpdatedBy(v int) *CurrencyUpsertOne {
	return u.Update(func(s *CurrencyUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *CurrencyUpsertOne) AddUpdatedBy(v int) *CurrencyUpsertOne {
	return u.Update(func(s *CurrencyUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *CurrencyUpsertOne) UpdateUpdatedBy() *CurrencyUpsertOne {
	return u.Update(func(s *CurrencyUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *CurrencyUpsertOne) ClearUpdatedBy() *CurrencyUpsertOne {
	return u.Update(func(s *CurrencyUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CurrencyUpsertOne) SetUpdatedAt(v time.Time) *CurrencyUpsertOne {
	return u.Update(func(s *CurrencyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CurrencyUpsertOne) UpdateUpdatedAt() *CurrencyUpsertOne {
	return u.Update(func(s *CurrencyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *CurrencyUpsertOne) ClearUpdatedAt() *CurrencyUpsertOne {
	return u.Update(func(s *CurrencyUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetCode sets the "code" field.
func (u *CurrencyUpsertOne) SetCode(v string) *CurrencyUpsertOne {
	return u.Update(func(s *CurrencyUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *CurrencyUpsertOne) UpdateCode() *CurrencyUpsertOne {
	return u.Update(func(s *CurrencyUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *CurrencyUpsertOne) SetName(v string) *CurrencyUpsertOne {
	return u.Update(func(s *CurrencyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CurrencyUpsertOne) UpdateName() *CurrencyUpsertOne {
	return u.Update(func(s *CurrencyUpsert) {
		s.UpdateName()
	})
}

// SetSign sets the "sign" field.
func (u *CurrencyUpsertOne) SetSign(v string) *CurrencyUpsertOne {
	return u.Update(func(s *CurrencyUpsert) {
		s.SetSign(v)
	})
}

// UpdateSign sets the "sign" field to the value that was provided on create.
func (u *CurrencyUpsertOne) UpdateSign() *CurrencyUpsertOne {
	return u.Update(func(s *CurrencyUpsert) {
		s.UpdateSign()
	})
}

// ClearSign clears the value of the "sign" field.
func (u *CurrencyUpsertOne) ClearSign() *CurrencyUpsertOne {
	return u.Update(func(s *CurrencyUpsert) {
		s.ClearSign()
	})
}

// SetStatus sets the "status" field.
func (u *CurrencyUpsertOne) SetStatus(v typex.SimpleStatus) *CurrencyUpsertOne {
	return u.Update(func(s *CurrencyUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CurrencyUpsertOne) UpdateStatus() *CurrencyUpsertOne {
	return u.Update(func(s *CurrencyUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *CurrencyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CurrencyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CurrencyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CurrencyUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CurrencyUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CurrencyCreateBulk is the builder for creating many Currency entities in bulk.
type CurrencyCreateBulk struct {
	config
	err      error
	builders []*CurrencyCreate
	conflict []sql.ConflictOption
}

// Save creates the Currency entities in the database.
func (_c *CurrencyCreateBulk) Save(ctx context.Context) ([]*Currency, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Currency, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CurrencyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CurrencyCreateBulk) SaveX(ctx context.Context) []*Currency {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CurrencyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CurrencyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Currency.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CurrencyUpsert) {
//			SetCreatedBy(v+v).
//		}).
//		Exec(ctx)
func (_c *CurrencyCreateBulk) OnConflict(opts ...sql.ConflictOption) *CurrencyUpsertBulk {
	_c.conflict = opts
	return &CurrencyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Currency.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CurrencyCreateBulk) OnConflictColumns(columns ...string) *CurrencyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CurrencyUpsertBulk{
		create: _c,
	}
}

// CurrencyUpsertBulk is the builder for "upsert"-ing
// a bulk of Currency nodes.
type CurrencyUpsertBulk struct {
	create *CurrencyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Currency.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(currency.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CurrencyUpsertBulk) UpdateNewValues() *CurrencyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(currency.FieldID)
			}
			if _, exists := b.mutation.CreatedBy(); exists {
				s.SetIgnore(currency.FieldCreatedBy)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(currency.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Currency.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CurrencyUpsertBulk) Ignore() *CurrencyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CurrencyUpsertBulk) DoNothing() *CurrencyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CurrencyCreateBulk.OnConflict
// documentation for more info.
func (u *CurrencyUpsertBulk) Update(set func(*CurrencyUpsert)) *CurrencyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CurrencyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *CurrencyUpsertBulk) SetUpdatedBy(v int) *CurrencyUpsertBulk {
	return u.Update(func(s *CurrencyUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *CurrencyUpsertBulk) AddUpdatedBy(v int) *CurrencyUpsertBulk {
	return u.Update(func(s *CurrencyUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *CurrencyUpsertBulk) UpdateUpdatedBy() *CurrencyUpsertBulk {
	return u.Update(func(s *CurrencyUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *CurrencyUpsertBulk) ClearUpdatedBy() *CurrencyUpsertBulk {
	return u.Update(func(s *CurrencyUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CurrencyUpsertBulk) SetUpdatedAt(v time.Time) *CurrencyUpsertBulk {
	return u.Update(func(s *CurrencyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CurrencyUpsertBulk) UpdateUpdatedAt() *CurrencyUpsertBulk {
	return u.Update(func(s *CurrencyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *CurrencyUpsertBulk) ClearUpdatedAt() *CurrencyUpsertBulk {
	return u.Update(func(s *CurrencyUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetCode sets the "code" field.
func (u *CurrencyUpsertBulk) SetCode(v string) *CurrencyUpsertBulk {
	return u.Update(func(s *CurrencyUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *CurrencyUpsertBulk) UpdateCode() *CurrencyUpsertBulk {
	return u.Update(func(s *CurrencyUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *CurrencyUpsertBulk) SetName(v string) *CurrencyUpsertBulk {
	return u.Update(func(s *CurrencyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CurrencyUpsertBulk) UpdateName() *CurrencyUpsertBulk {
	return u.Update(func(s *CurrencyUpsert) {
		s.UpdateName()
	})
}

// SetSign sets the "sign" field.
func (u *CurrencyUpsertBulk) SetSign(v string) *CurrencyUpsertBulk {
	return u.Update(func(s *CurrencyUpsert) {
		s.SetSign(v)
	})
}

// UpdateSign sets the "sign" field to the value that was provided on create.
func (u *CurrencyUpsertBulk) UpdateSign() *CurrencyUpsertBulk {
	return u.Update(func(s *CurrencyUpsert) {
		s.UpdateSign()
	})
}

// ClearSign clears the value of the "sign" field.
func (u *CurrencyUpsertBulk) ClearSign() *CurrencyUpsertBulk {
	return u.Update(func(s *CurrencyUpsert) {
		s.ClearSign()
	})
}

// SetStatus sets the "status" field.
func (u *CurrencyUpsertBulk) SetStatus(v typex.SimpleStatus) *CurrencyUpsertBulk {
	return u.Update(func(s *CurrencyUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CurrencyUpsertBulk) UpdateStatus() *CurrencyUpsertBulk {
	return u.Update(func(s *CurrencyUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *CurrencyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CurrencyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CurrencyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CurrencyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
