// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/woocoos/knockout/ent/filesource"
)

// FileSource is the model entity for the FileSource schema.
type FileSource struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy int `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy int `json:"updated_by,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 文件来源
	Kind filesource.Kind `json:"kind,omitempty"`
	// 备注
	Comments string `json:"comments,omitempty"`
	// 对外服务的访问域名
	Endpoint string `json:"endpoint,omitempty"`
	// 是否禁止修改endpoint，如果是自定义域名设为true
	EndpointImmutable bool `json:"endpoint_immutable,omitempty"`
	// sts服务的访问域名
	StsEndpoint string `json:"sts_endpoint,omitempty"`
	// 地域，数据存储的物理位置
	Region string `json:"region,omitempty"`
	// 文件存储空间
	Bucket string `json:"bucket,omitempty"`
	// 文件存储空间地址，用于匹配url
	BucketURL string `json:"bucket_url,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FileSourceQuery when eager-loading is set.
	Edges        FileSourceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FileSourceEdges holds the relations/edges for other nodes in the graph.
type FileSourceEdges struct {
	// 来源凭证
	Identities []*FileIdentity `json:"identities,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool

	namedIdentities map[string][]*FileIdentity
}

// IdentitiesOrErr returns the Identities value or an error if the edge
// was not loaded in eager-loading.
func (e FileSourceEdges) IdentitiesOrErr() ([]*FileIdentity, error) {
	if e.loadedTypes[0] {
		return e.Identities, nil
	}
	return nil, &NotLoadedError{edge: "identities"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FileSource) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case filesource.FieldEndpointImmutable:
			values[i] = new(sql.NullBool)
		case filesource.FieldID, filesource.FieldCreatedBy, filesource.FieldUpdatedBy:
			values[i] = new(sql.NullInt64)
		case filesource.FieldKind, filesource.FieldComments, filesource.FieldEndpoint, filesource.FieldStsEndpoint, filesource.FieldRegion, filesource.FieldBucket, filesource.FieldBucketURL:
			values[i] = new(sql.NullString)
		case filesource.FieldCreatedAt, filesource.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FileSource fields.
func (_m *FileSource) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case filesource.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case filesource.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = int(value.Int64)
			}
		case filesource.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case filesource.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = int(value.Int64)
			}
		case filesource.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case filesource.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = filesource.Kind(value.String)
			}
		case filesource.FieldComments:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field comments", values[i])
			} else if value.Valid {
				_m.Comments = value.String
			}
		case filesource.FieldEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field endpoint", values[i])
			} else if value.Valid {
				_m.Endpoint = value.String
			}
		case filesource.FieldEndpointImmutable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field endpoint_immutable", values[i])
			} else if value.Valid {
				_m.EndpointImmutable = value.Bool
			}
		case filesource.FieldStsEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sts_endpoint", values[i])
			} else if value.Valid {
				_m.StsEndpoint = value.String
			}
		case filesource.FieldRegion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field region", values[i])
			} else if value.Valid {
				_m.Region = value.String
			}
		case filesource.FieldBucket:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bucket", values[i])
			} else if value.Valid {
				_m.Bucket = value.String
			}
		case filesource.FieldBucketURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bucket_url", values[i])
			} else if value.Valid {
				_m.BucketURL = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FileSource.
// This includes values selected through modifiers, order, etc.
func (_m *FileSource) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryIdentities queries the "identities" edge of the FileSource entity.
func (_m *FileSource) QueryIdentities() *FileIdentityQuery {
	return NewFileSourceClient(_m.config).QueryIdentities(_m)
}

// Update returns a builder for updating this FileSource.
// Note that you need to call FileSource.Unwrap() before calling this method if this FileSource
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FileSource) Update() *FileSourceUpdateOne {
	return NewFileSourceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FileSource entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FileSource) Unwrap() *FileSource {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FileSource is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FileSource) String() string {
	var builder strings.Builder
	builder.WriteString("FileSource(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedBy))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.Kind))
	builder.WriteString(", ")
	builder.WriteString("comments=")
	builder.WriteString(_m.Comments)
	builder.WriteString(", ")
	builder.WriteString("endpoint=")
	builder.WriteString(_m.Endpoint)
	builder.WriteString(", ")
	builder.WriteString("endpoint_immutable=")
	builder.WriteString(fmt.Sprintf("%v", _m.EndpointImmutable))
	builder.WriteString(", ")
	builder.WriteString("sts_endpoint=")
	builder.WriteString(_m.StsEndpoint)
	builder.WriteString(", ")
	builder.WriteString("region=")
	builder.WriteString(_m.Region)
	builder.WriteString(", ")
	builder.WriteString("bucket=")
	builder.WriteString(_m.Bucket)
	builder.WriteString(", ")
	builder.WriteString("bucket_url=")
	builder.WriteString(_m.BucketURL)
	builder.WriteByte(')')
	return builder.String()
}

// NamedIdentities returns the Identities named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *FileSource) NamedIdentities(name string) ([]*FileIdentity, error) {
	if _m.Edges.namedIdentities == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedIdentities[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *FileSource) appendNamedIdentities(name string, edges ...*FileIdentity) {
	if _m.Edges.namedIdentities == nil {
		_m.Edges.namedIdentities = make(map[string][]*FileIdentity)
	}
	if len(edges) == 0 {
		_m.Edges.namedIdentities[name] = []*FileIdentity{}
	} else {
		_m.Edges.namedIdentities[name] = append(_m.Edges.namedIdentities[name], edges...)
	}
}

// FileSources is a parsable slice of FileSource.
type FileSources []*FileSource
