// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/woocoos/knockout/ent/fileidentity"
	"github.com/woocoos/knockout/ent/filesource"
	"github.com/woocoos/knockout/ent/predicate"
)

// FileSourceUpdate is the builder for updating FileSource entities.
type FileSourceUpdate struct {
	config
	hooks    []Hook
	mutation *FileSourceMutation
}

// Where appends a list predicates to the FileSourceUpdate builder.
func (_u *FileSourceUpdate) Where(ps ...predicate.FileSource) *FileSourceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *FileSourceUpdate) SetUpdatedBy(v int) *FileSourceUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *FileSourceUpdate) SetNillableUpdatedBy(v *int) *FileSourceUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *FileSourceUpdate) AddUpdatedBy(v int) *FileSourceUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *FileSourceUpdate) ClearUpdatedBy() *FileSourceUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FileSourceUpdate) SetUpdatedAt(v time.Time) *FileSourceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *FileSourceUpdate) SetNillableUpdatedAt(v *time.Time) *FileSourceUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *FileSourceUpdate) ClearUpdatedAt() *FileSourceUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetKind sets the "kind" field.
func (_u *FileSourceUpdate) SetKind(v filesource.Kind) *FileSourceUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *FileSourceUpdate) SetNillableKind(v *filesource.Kind) *FileSourceUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetComments sets the "comments" field.
func (_u *FileSourceUpdate) SetComments(v string) *FileSourceUpdate {
	_u.mutation.SetComments(v)
	return _u
}

// SetNillableComments sets the "comments" field if the given value is not nil.
func (_u *FileSourceUpdate) SetNillableComments(v *string) *FileSourceUpdate {
	if v != nil {
		_u.SetComments(*v)
	}
	return _u
}

// ClearComments clears the value of the "comments" field.
func (_u *FileSourceUpdate) ClearComments() *FileSourceUpdate {
	_u.mutation.ClearComments()
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *FileSourceUpdate) SetEndpoint(v string) *FileSourceUpdate {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *FileSourceUpdate) SetNillableEndpoint(v *string) *FileSourceUpdate {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// SetEndpointImmutable sets the "endpoint_immutable" field.
func (_u *FileSourceUpdate) SetEndpointImmutable(v bool) *FileSourceUpdate {
	_u.mutation.SetEndpointImmutable(v)
	return _u
}

// SetNillableEndpointImmutable sets the "endpoint_immutable" field if the given value is not nil.
func (_u *FileSourceUpdate) SetNillableEndpointImmutable(v *bool) *FileSourceUpdate {
	if v != nil {
		_u.SetEndpointImmutable(*v)
	}
	return _u
}

// SetStsEndpoint sets the "sts_endpoint" field.
func (_u *FileSourceUpdate) SetStsEndpoint(v string) *FileSourceUpdate {
	_u.mutation.SetStsEndpoint(v)
	return _u
}

// SetNillableStsEndpoint sets the "sts_endpoint" field if the given value is not nil.
func (_u *FileSourceUpdate) SetNillableStsEndpoint(v *string) *FileSourceUpdate {
	if v != nil {
		_u.SetStsEndpoint(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *FileSourceUpdate) SetRegion(v string) *FileSourceUpdate {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *FileSourceUpdate) SetNillableRegion(v *string) *FileSourceUpdate {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetBucket sets the "bucket" field.
func (_u *FileSourceUpdate) SetBucket(v string) *FileSourceUpdate {
	_u.mutation.SetBucket(v)
	return _u
}

// SetNillableBucket sets the "bucket" field if the given value is not nil.
func (_u *FileSourceUpdate) SetNillableBucket(v *string) *FileSourceUpdate {
	if v != nil {
		_u.SetBucket(*v)
	}
	return _u
}

// SetBucketURL sets the "bucket_url" field.
func (_u *FileSourceUpdate) SetBucketURL(v string) *FileSourceUpdate {
	_u.mutation.SetBucketURL(v)
	return _u
}

// SetNillableBucketURL sets the "bucket_url" field if the given value is not nil.
func (_u *FileSourceUpdate) SetNillableBucketURL(v *string) *FileSourceUpdate {
	if v != nil {
		_u.SetBucketURL(*v)
	}
	return _u
}

// AddIdentityIDs adds the "identities" edge to the FileIdentity entity by IDs.
func (_u *FileSourceUpdate) AddIdentityIDs(ids ...int) *FileSourceUpdate {
	_u.mutation.AddIdentityIDs(ids...)
	return _u
}

// AddIdentities adds the "identities" edges to the FileIdentity entity.
func (_u *FileSourceUpdate) AddIdentities(v ...*FileIdentity) *FileSourceUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddIdentityIDs(ids...)
}

// Mutation returns the FileSourceMutation object of the builder.
func (_u *FileSourceUpdate) Mutation() *FileSourceMutation {
	return _u.mutation
}

// ClearIdentities clears all "identities" edges to the FileIdentity entity.
func (_u *FileSourceUpdate) ClearIdentities() *FileSourceUpdate {
	_u.mutation.ClearIdentities()
	return _u
}

// RemoveIdentityIDs removes the "identities" edge to FileIdentity entities by IDs.
func (_u *FileSourceUpdate) RemoveIdentityIDs(ids ...int) *FileSourceUpdate {
	_u.mutation.RemoveIdentityIDs(ids...)
	return _u
}

// RemoveIdentities removes "identities" edges to FileIdentity entities.
func (_u *FileSourceUpdate) RemoveIdentities(v ...*FileIdentity) *FileSourceUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveIdentityIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FileSourceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FileSourceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FileSourceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FileSourceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FileSourceUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := filesource.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "FileSource.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Endpoint(); ok {
		if err := filesource.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "FileSource.endpoint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StsEndpoint(); ok {
		if err := filesource.StsEndpointValidator(v); err != nil {
			return &ValidationError{Name: "sts_endpoint", err: fmt.Errorf(`ent: validator failed for field "FileSource.sts_endpoint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Region(); ok {
		if err := filesource.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "FileSource.region": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Bucket(); ok {
		if err := filesource.BucketValidator(v); err != nil {
			return &ValidationError{Name: "bucket", err: fmt.Errorf(`ent: validator failed for field "FileSource.bucket": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BucketURL(); ok {
		if err := filesource.BucketURLValidator(v); err != nil {
			return &ValidationError{Name: "bucket_url", err: fmt.Errorf(`ent: validator failed for field "FileSource.bucket_url": %w`, err)}
		}
	}
	return nil
}

func (_u *FileSourceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(filesource.Table, filesource.Columns, sqlgraph.NewFieldSpec(filesource.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(filesource.FieldUpdatedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(filesource.FieldUpdatedBy, field.TypeInt, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(filesource.FieldUpdatedBy, field.TypeInt)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(filesource.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(filesource.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(filesource.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Comments(); ok {
		_spec.SetField(filesource.FieldComments, field.TypeString, value)
	}
	if _u.mutation.CommentsCleared() {
		_spec.ClearField(filesource.FieldComments, field.TypeString)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(filesource.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.EndpointImmutable(); ok {
		_spec.SetField(filesource.FieldEndpointImmutable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StsEndpoint(); ok {
		_spec.SetField(filesource.FieldStsEndpoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(filesource.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bucket(); ok {
		_spec.SetField(filesource.FieldBucket, field.TypeString, value)
	}
	if value, ok := _u.mutation.BucketURL(); ok {
		_spec.SetField(filesource.FieldBucketURL, field.TypeString, value)
	}
	if _u.mutation.IdentitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   filesource.IdentitiesTable,
			Columns: []string{filesource.IdentitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fileidentity.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedIdentitiesIDs(); len(nodes) > 0 && !_u.mutation.IdentitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   filesource.IdentitiesTable,
			Columns: []string{filesource.IdentitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fileidentity.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IdentitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   filesource.IdentitiesTable,
			Columns: []string{filesource.IdentitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fileidentity.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{filesource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FileSourceUpdateOne is the builder for updating a single FileSource entity.
type FileSourceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FileSourceMutation
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *FileSourceUpdateOne) SetUpdatedBy(v int) *FileSourceUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *FileSourceUpdateOne) SetNillableUpdatedBy(v *int) *FileSourceUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *FileSourceUpdateOne) AddUpdatedBy(v int) *FileSourceUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *FileSourceUpdateOne) ClearUpdatedBy() *FileSourceUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FileSourceUpdateOne) SetUpdatedAt(v time.Time) *FileSourceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *FileSourceUpdateOne) SetNillableUpdatedAt(v *time.Time) *FileSourceUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *FileSourceUpdateOne) ClearUpdatedAt() *FileSourceUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetKind sets the "kind" field.
func (_u *FileSourceUpdateOne) SetKind(v filesource.Kind) *FileSourceUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *FileSourceUpdateOne) SetNillableKind(v *filesource.Kind) *FileSourceUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetComments sets the "comments" field.
func (_u *FileSourceUpdateOne) SetComments(v string) *FileSourceUpdateOne {
	_u.mutation.SetComments(v)
	return _u
}

// SetNillableComments sets the "comments" field if the given value is not nil.
func (_u *FileSourceUpdateOne) SetNillableComments(v *string) *FileSourceUpdateOne {
	if v != nil {
		_u.SetComments(*v)
	}
	return _u
}

// ClearComments clears the value of the "comments" field.
func (_u *FileSourceUpdateOne) ClearComments() *FileSourceUpdateOne {
	_u.mutation.ClearComments()
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *FileSourceUpdateOne) SetEndpoint(v string) *FileSourceUpdateOne {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *FileSourceUpdateOne) SetNillableEndpoint(v *string) *FileSourceUpdateOne {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// SetEndpointImmutable sets the "endpoint_immutable" field.
func (_u *FileSourceUpdateOne) SetEndpointImmutable(v bool) *FileSourceUpdateOne {
	_u.mutation.SetEndpointImmutable(v)
	return _u
}

// SetNillableEndpointImmutable sets the "endpoint_immutable" field if the given value is not nil.
func (_u *FileSourceUpdateOne) SetNillableEndpointImmutable(v *bool) *FileSourceUpdateOne {
	if v != nil {
		_u.SetEndpointImmutable(*v)
	}
	return _u
}

// SetStsEndpoint sets the "sts_endpoint" field.
func (_u *FileSourceUpdateOne) SetStsEndpoint(v string) *FileSourceUpdateOne {
	_u.mutation.SetStsEndpoint(v)
	return _u
}

// SetNillableStsEndpoint sets the "sts_endpoint" field if the given value is not nil.
func (_u *FileSourceUpdateOne) SetNillableStsEndpoint(v *string) *FileSourceUpdateOne {
	if v != nil {
		_u.SetStsEndpoint(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *FileSourceUpdateOne) SetRegion(v string) *FileSourceUpdateOne {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *FileSourceUpdateOne) SetNillableRegion(v *string) *FileSourceUpdateOne {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetBucket sets the "bucket" field.
func (_u *FileSourceUpdateOne) SetBucket(v string) *FileSourceUpdateOne {
	_u.mutation.SetBucket(v)
	return _u
}

// SetNillableBucket sets the "bucket" field if the given value is not nil.
func (_u *FileSourceUpdateOne) SetNillableBucket(v *string) *FileSourceUpdateOne {
	if v != nil {
		_u.SetBucket(*v)
	}
	return _u
}

// SetBucketURL sets the "bucket_url" field.
func (_u *FileSourceUpdateOne) SetBucketURL(v string) *FileSourceUpdateOne {
	_u.mutation.SetBucketURL(v)
	return _u
}

// SetNillableBucketURL sets the "bucket_url" field if the given value is not nil.
func (_u *FileSourceUpdateOne) SetNillableBucketURL(v *string) *FileSourceUpdateOne {
	if v != nil {
		_u.SetBucketURL(*v)
	}
	return _u
}

// AddIdentityIDs adds the "identities" edge to the FileIdentity entity by IDs.
func (_u *FileSourceUpdateOne) AddIdentityIDs(ids ...int) *FileSourceUpdateOne {
	_u.mutation.AddIdentityIDs(ids...)
	return _u
}

// AddIdentities adds the "identities" edges to the FileIdentity entity.
func (_u *FileSourceUpdateOne) AddIdentities(v ...*FileIdentity) *FileSourceUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddIdentityIDs(ids...)
}

// Mutation returns the FileSourceMutation object of the builder.
func (_u *FileSourceUpdateOne) Mutation() *FileSourceMutation {
	return _u.mutation
}

// ClearIdentities clears all "identities" edges to the FileIdentity entity.
func (_u *FileSourceUpdateOne) ClearIdentities() *FileSourceUpdateOne {
	_u.mutation.ClearIdentities()
	return _u
}

// RemoveIdentityIDs removes the "identities" edge to FileIdentity entities by IDs.
func (_u *FileSourceUpdateOne) RemoveIdentityIDs(ids ...int) *FileSourceUpdateOne {
	_u.mutation.RemoveIdentityIDs(ids...)
	return _u
}

// RemoveIdentities removes "identities" edges to FileIdentity entities.
func (_u *FileSourceUpdateOne) RemoveIdentities(v ...*FileIdentity) *FileSourceUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveIdentityIDs(ids...)
}

// Where appends a list predicates to the FileSourceUpdate builder.
func (_u *FileSourceUpdateOne) Where(ps ...predicate.FileSource) *FileSourceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FileSourceUpdateOne) Select(field string, fields ...string) *FileSourceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FileSource entity.
func (_u *FileSourceUpdateOne) Save(ctx context.Context) (*FileSource, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FileSourceUpdateOne) SaveX(ctx context.Context) *FileSource {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FileSourceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FileSourceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FileSourceUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := filesource.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "FileSource.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Endpoint(); ok {
		if err := filesource.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "FileSource.endpoint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StsEndpoint(); ok {
		if err := filesource.StsEndpointValidator(v); err != nil {
			return &ValidationError{Name: "sts_endpoint", err: fmt.Errorf(`ent: validator failed for field "FileSource.sts_endpoint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Region(); ok {
		if err := filesource.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "FileSource.region": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Bucket(); ok {
		if err := filesource.BucketValidator(v); err != nil {
			return &ValidationError{Name: "bucket", err: fmt.Errorf(`ent: validator failed for field "FileSource.bucket": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BucketURL(); ok {
		if err := filesource.BucketURLValidator(v); err != nil {
			return &ValidationError{Name: "bucket_url", err: fmt.Errorf(`ent: validator failed for field "FileSource.bucket_url": %w`, err)}
		}
	}
	return nil
}

func (_u *FileSourceUpdateOne) sqlSave(ctx context.Context) (_node *FileSource, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(filesource.Table, filesource.Columns, sqlgraph.NewFieldSpec(filesource.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FileSource.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, filesource.FieldID)
		for _, f := range fields {
			if !filesource.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != filesource.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(filesource.FieldUpdatedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(filesource.FieldUpdatedBy, field.TypeInt, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(filesource.FieldUpdatedBy, field.TypeInt)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(filesource.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(filesource.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(filesource.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Comments(); ok {
		_spec.SetField(filesource.FieldComments, field.TypeString, value)
	}
	if _u.mutation.CommentsCleared() {
		_spec.ClearField(filesource.FieldComments, field.TypeString)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(filesource.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.EndpointImmutable(); ok {
		_spec.SetField(filesource.FieldEndpointImmutable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StsEndpoint(); ok {
		_spec.SetField(filesource.FieldStsEndpoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(filesource.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bucket(); ok {
		_spec.SetField(filesource.FieldBucket, field.TypeString, value)
	}
	if value, ok := _u.mutation.BucketURL(); ok {
		_spec.SetField(filesource.FieldBucketURL, field.TypeString, value)
	}
	if _u.mutation.IdentitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   filesource.IdentitiesTable,
			Columns: []string{filesource.IdentitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fileidentity.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedIdentitiesIDs(); len(nodes) > 0 && !_u.mutation.IdentitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   filesource.IdentitiesTable,
			Columns: []string{filesource.IdentitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fileidentity.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IdentitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   filesource.IdentitiesTable,
			Columns: []string{filesource.IdentitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fileidentity.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &FileSource{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{filesource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
