// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/woocoos/knockout/ent/app"
	"github.com/woocoos/knockout/ent/org"
	"github.com/woocoos/knockout/ent/orgapp"
	"github.com/woocoos/knockout/ent/predicate"
)

// OrgAppUpdate is the builder for updating OrgApp entities.
type OrgAppUpdate struct {
	config
	hooks    []Hook
	mutation *OrgAppMutation
}

// Where appends a list predicates to the OrgAppUpdate builder.
func (_u *OrgAppUpdate) Where(ps ...predicate.OrgApp) *OrgAppUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *OrgAppUpdate) SetUpdatedBy(v int) *OrgAppUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *OrgAppUpdate) SetNillableUpdatedBy(v *int) *OrgAppUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *OrgAppUpdate) AddUpdatedBy(v int) *OrgAppUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *OrgAppUpdate) ClearUpdatedBy() *OrgAppUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrgAppUpdate) SetUpdatedAt(v time.Time) *OrgAppUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *OrgAppUpdate) SetNillableUpdatedAt(v *time.Time) *OrgAppUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *OrgAppUpdate) ClearUpdatedAt() *OrgAppUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetOrgID sets the "org_id" field.
func (_u *OrgAppUpdate) SetOrgID(v int) *OrgAppUpdate {
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *OrgAppUpdate) SetNillableOrgID(v *int) *OrgAppUpdate {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *OrgAppUpdate) SetAppID(v int) *OrgAppUpdate {
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *OrgAppUpdate) SetNillableAppID(v *int) *OrgAppUpdate {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// SetApp sets the "app" edge to the App entity.
func (_u *OrgAppUpdate) SetApp(v *App) *OrgAppUpdate {
	return _u.SetAppID(v.ID)
}

// SetOrg sets the "org" edge to the Org entity.
func (_u *OrgAppUpdate) SetOrg(v *Org) *OrgAppUpdate {
	return _u.SetOrgID(v.ID)
}

// Mutation returns the OrgAppMutation object of the builder.
func (_u *OrgAppUpdate) Mutation() *OrgAppMutation {
	return _u.mutation
}

// ClearApp clears the "app" edge to the App entity.
func (_u *OrgAppUpdate) ClearApp() *OrgAppUpdate {
	_u.mutation.ClearApp()
	return _u
}

// ClearOrg clears the "org" edge to the Org entity.
func (_u *OrgAppUpdate) ClearOrg() *OrgAppUpdate {
	_u.mutation.ClearOrg()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrgAppUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrgAppUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrgAppUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrgAppUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrgAppUpdate) check() error {
	if _u.mutation.AppCleared() && len(_u.mutation.AppIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrgApp.app"`)
	}
	if _u.mutation.OrgCleared() && len(_u.mutation.OrgIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrgApp.org"`)
	}
	return nil
}

func (_u *OrgAppUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(orgapp.Table, orgapp.Columns, sqlgraph.NewFieldSpec(orgapp.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(orgapp.FieldUpdatedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(orgapp.FieldUpdatedBy, field.TypeInt, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(orgapp.FieldUpdatedBy, field.TypeInt)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(orgapp.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(orgapp.FieldUpdatedAt, field.TypeTime)
	}
	if _u.mutation.AppCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   orgapp.AppTable,
			Columns: []string{orgapp.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   orgapp.AppTable,
			Columns: []string{orgapp.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrgCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   orgapp.OrgTable,
			Columns: []string{orgapp.OrgColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(org.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrgIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   orgapp.OrgTable,
			Columns: []string{orgapp.OrgColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(org.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orgapp.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrgAppUpdateOne is the builder for updating a single OrgApp entity.
type OrgAppUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrgAppMutation
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *OrgAppUpdateOne) SetUpdatedBy(v int) *OrgAppUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *OrgAppUpdateOne) SetNillableUpdatedBy(v *int) *OrgAppUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *OrgAppUpdateOne) AddUpdatedBy(v int) *OrgAppUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *OrgAppUpdateOne) ClearUpdatedBy() *OrgAppUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrgAppUpdateOne) SetUpdatedAt(v time.Time) *OrgAppUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *OrgAppUpdateOne) SetNillableUpdatedAt(v *time.Time) *OrgAppUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *OrgAppUpdateOne) ClearUpdatedAt() *OrgAppUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetOrgID sets the "org_id" field.
func (_u *OrgAppUpdateOne) SetOrgID(v int) *OrgAppUpdateOne {
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *OrgAppUpdateOne) SetNillableOrgID(v *int) *OrgAppUpdateOne {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *OrgAppUpdateOne) SetAppID(v int) *OrgAppUpdateOne {
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *OrgAppUpdateOne) SetNillableAppID(v *int) *OrgAppUpdateOne {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// SetApp sets the "app" edge to the App entity.
func (_u *OrgAppUpdateOne) SetApp(v *App) *OrgAppUpdateOne {
	return _u.SetAppID(v.ID)
}

// SetOrg sets the "org" edge to the Org entity.
func (_u *OrgAppUpdateOne) SetOrg(v *Org) *OrgAppUpdateOne {
	return _u.SetOrgID(v.ID)
}

// Mutation returns the OrgAppMutation object of the builder.
func (_u *OrgAppUpdateOne) Mutation() *OrgAppMutation {
	return _u.mutation
}

// ClearApp clears the "app" edge to the App entity.
func (_u *OrgAppUpdateOne) ClearApp() *OrgAppUpdateOne {
	_u.mutation.ClearApp()
	return _u
}

// ClearOrg clears the "org" edge to the Org entity.
func (_u *OrgAppUpdateOne) ClearOrg() *OrgAppUpdateOne {
	_u.mutation.ClearOrg()
	return _u
}

// Where appends a list predicates to the OrgAppUpdate builder.
func (_u *OrgAppUpdateOne) Where(ps ...predicate.OrgApp) *OrgAppUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrgAppUpdateOne) Select(field string, fields ...string) *OrgAppUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OrgApp entity.
func (_u *OrgAppUpdateOne) Save(ctx context.Context) (*OrgApp, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrgAppUpdateOne) SaveX(ctx context.Context) *OrgApp {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrgAppUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrgAppUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrgAppUpdateOne) check() error {
	if _u.mutation.AppCleared() && len(_u.mutation.AppIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrgApp.app"`)
	}
	if _u.mutation.OrgCleared() && len(_u.mutation.OrgIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrgApp.org"`)
	}
	return nil
}

func (_u *OrgAppUpdateOne) sqlSave(ctx context.Context) (_node *OrgApp, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(orgapp.Table, orgapp.Columns, sqlgraph.NewFieldSpec(orgapp.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OrgApp.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, orgapp.FieldID)
		for _, f := range fields {
			if !orgapp.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != orgapp.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(orgapp.FieldUpdatedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(orgapp.FieldUpdatedBy, field.TypeInt, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(orgapp.FieldUpdatedBy, field.TypeInt)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(orgapp.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(orgapp.FieldUpdatedAt, field.TypeTime)
	}
	if _u.mutation.AppCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   orgapp.AppTable,
			Columns: []string{orgapp.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   orgapp.AppTable,
			Columns: []string{orgapp.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrgCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   orgapp.OrgTable,
			Columns: []string{orgapp.OrgColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(org.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrgIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   orgapp.OrgTable,
			Columns: []string{orgapp.OrgColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(org.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OrgApp{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orgapp.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
