// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/woocoos/knockout/ent/predicate"
	"github.com/woocoos/knockout/ent/userpasswordpolicy"
)

// UserPasswordPolicyUpdate is the builder for updating UserPasswordPolicy entities.
type UserPasswordPolicyUpdate struct {
	config
	hooks    []Hook
	mutation *UserPasswordPolicyMutation
}

// Where appends a list predicates to the UserPasswordPolicyUpdate builder.
func (_u *UserPasswordPolicyUpdate) Where(ps ...predicate.UserPasswordPolicy) *UserPasswordPolicyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *UserPasswordPolicyUpdate) SetUpdatedBy(v int) *UserPasswordPolicyUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *UserPasswordPolicyUpdate) SetNillableUpdatedBy(v *int) *UserPasswordPolicyUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *UserPasswordPolicyUpdate) AddUpdatedBy(v int) *UserPasswordPolicyUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *UserPasswordPolicyUpdate) ClearUpdatedBy() *UserPasswordPolicyUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserPasswordPolicyUpdate) SetUpdatedAt(v time.Time) *UserPasswordPolicyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *UserPasswordPolicyUpdate) SetNillableUpdatedAt(v *time.Time) *UserPasswordPolicyUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *UserPasswordPolicyUpdate) ClearUpdatedAt() *UserPasswordPolicyUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetLength sets the "length" field.
func (_u *UserPasswordPolicyUpdate) SetLength(v int32) *UserPasswordPolicyUpdate {
	_u.mutation.ResetLength()
	_u.mutation.SetLength(v)
	return _u
}

// SetNillableLength sets the "length" field if the given value is not nil.
func (_u *UserPasswordPolicyUpdate) SetNillableLength(v *int32) *UserPasswordPolicyUpdate {
	if v != nil {
		_u.SetLength(*v)
	}
	return _u
}

// AddLength adds value to the "length" field.
func (_u *UserPasswordPolicyUpdate) AddLength(v int32) *UserPasswordPolicyUpdate {
	_u.mutation.AddLength(v)
	return _u
}

// ClearLength clears the value of the "length" field.
func (_u *UserPasswordPolicyUpdate) ClearLength() *UserPasswordPolicyUpdate {
	_u.mutation.ClearLength()
	return _u
}

// SetIncludeElement sets the "include_element" field.
func (_u *UserPasswordPolicyUpdate) SetIncludeElement(v int32) *UserPasswordPolicyUpdate {
	_u.mutation.ResetIncludeElement()
	_u.mutation.SetIncludeElement(v)
	return _u
}

// SetNillableIncludeElement sets the "include_element" field if the given value is not nil.
func (_u *UserPasswordPolicyUpdate) SetNillableIncludeElement(v *int32) *UserPasswordPolicyUpdate {
	if v != nil {
		_u.SetIncludeElement(*v)
	}
	return _u
}

// AddIncludeElement adds value to the "include_element" field.
func (_u *UserPasswordPolicyUpdate) AddIncludeElement(v int32) *UserPasswordPolicyUpdate {
	_u.mutation.AddIncludeElement(v)
	return _u
}

// ClearIncludeElement clears the value of the "include_element" field.
func (_u *UserPasswordPolicyUpdate) ClearIncludeElement() *UserPasswordPolicyUpdate {
	_u.mutation.ClearIncludeElement()
	return _u
}

// SetIncludeChar sets the "include_char" field.
func (_u *UserPasswordPolicyUpdate) SetIncludeChar(v int32) *UserPasswordPolicyUpdate {
	_u.mutation.ResetIncludeChar()
	_u.mutation.SetIncludeChar(v)
	return _u
}

// SetNillableIncludeChar sets the "include_char" field if the given value is not nil.
func (_u *UserPasswordPolicyUpdate) SetNillableIncludeChar(v *int32) *UserPasswordPolicyUpdate {
	if v != nil {
		_u.SetIncludeChar(*v)
	}
	return _u
}

// AddIncludeChar adds value to the "include_char" field.
func (_u *UserPasswordPolicyUpdate) AddIncludeChar(v int32) *UserPasswordPolicyUpdate {
	_u.mutation.AddIncludeChar(v)
	return _u
}

// ClearIncludeChar clears the value of the "include_char" field.
func (_u *UserPasswordPolicyUpdate) ClearIncludeChar() *UserPasswordPolicyUpdate {
	_u.mutation.ClearIncludeChar()
	return _u
}

// SetAllowIncludeUserName sets the "allow_include_user_name" field.
func (_u *UserPasswordPolicyUpdate) SetAllowIncludeUserName(v bool) *UserPasswordPolicyUpdate {
	_u.mutation.SetAllowIncludeUserName(v)
	return _u
}

// SetNillableAllowIncludeUserName sets the "allow_include_user_name" field if the given value is not nil.
func (_u *UserPasswordPolicyUpdate) SetNillableAllowIncludeUserName(v *bool) *UserPasswordPolicyUpdate {
	if v != nil {
		_u.SetAllowIncludeUserName(*v)
	}
	return _u
}

// ClearAllowIncludeUserName clears the value of the "allow_include_user_name" field.
func (_u *UserPasswordPolicyUpdate) ClearAllowIncludeUserName() *UserPasswordPolicyUpdate {
	_u.mutation.ClearAllowIncludeUserName()
	return _u
}

// SetInvalidDay sets the "invalid_day" field.
func (_u *UserPasswordPolicyUpdate) SetInvalidDay(v int32) *UserPasswordPolicyUpdate {
	_u.mutation.ResetInvalidDay()
	_u.mutation.SetInvalidDay(v)
	return _u
}

// SetNillableInvalidDay sets the "invalid_day" field if the given value is not nil.
func (_u *UserPasswordPolicyUpdate) SetNillableInvalidDay(v *int32) *UserPasswordPolicyUpdate {
	if v != nil {
		_u.SetInvalidDay(*v)
	}
	return _u
}

// AddInvalidDay adds value to the "invalid_day" field.
func (_u *UserPasswordPolicyUpdate) AddInvalidDay(v int32) *UserPasswordPolicyUpdate {
	_u.mutation.AddInvalidDay(v)
	return _u
}

// ClearInvalidDay clears the value of the "invalid_day" field.
func (_u *UserPasswordPolicyUpdate) ClearInvalidDay() *UserPasswordPolicyUpdate {
	_u.mutation.ClearInvalidDay()
	return _u
}

// SetInvalidLoginLimit sets the "invalid_login_limit" field.
func (_u *UserPasswordPolicyUpdate) SetInvalidLoginLimit(v bool) *UserPasswordPolicyUpdate {
	_u.mutation.SetInvalidLoginLimit(v)
	return _u
}

// SetNillableInvalidLoginLimit sets the "invalid_login_limit" field if the given value is not nil.
func (_u *UserPasswordPolicyUpdate) SetNillableInvalidLoginLimit(v *bool) *UserPasswordPolicyUpdate {
	if v != nil {
		_u.SetInvalidLoginLimit(*v)
	}
	return _u
}

// ClearInvalidLoginLimit clears the value of the "invalid_login_limit" field.
func (_u *UserPasswordPolicyUpdate) ClearInvalidLoginLimit() *UserPasswordPolicyUpdate {
	_u.mutation.ClearInvalidLoginLimit()
	return _u
}

// SetRetry sets the "retry" field.
func (_u *UserPasswordPolicyUpdate) SetRetry(v int32) *UserPasswordPolicyUpdate {
	_u.mutation.ResetRetry()
	_u.mutation.SetRetry(v)
	return _u
}

// SetNillableRetry sets the "retry" field if the given value is not nil.
func (_u *UserPasswordPolicyUpdate) SetNillableRetry(v *int32) *UserPasswordPolicyUpdate {
	if v != nil {
		_u.SetRetry(*v)
	}
	return _u
}

// AddRetry adds value to the "retry" field.
func (_u *UserPasswordPolicyUpdate) AddRetry(v int32) *UserPasswordPolicyUpdate {
	_u.mutation.AddRetry(v)
	return _u
}

// ClearRetry clears the value of the "retry" field.
func (_u *UserPasswordPolicyUpdate) ClearRetry() *UserPasswordPolicyUpdate {
	_u.mutation.ClearRetry()
	return _u
}

// SetCaptchaTimes sets the "captcha_times" field.
func (_u *UserPasswordPolicyUpdate) SetCaptchaTimes(v int32) *UserPasswordPolicyUpdate {
	_u.mutation.ResetCaptchaTimes()
	_u.mutation.SetCaptchaTimes(v)
	return _u
}

// SetNillableCaptchaTimes sets the "captcha_times" field if the given value is not nil.
func (_u *UserPasswordPolicyUpdate) SetNillableCaptchaTimes(v *int32) *UserPasswordPolicyUpdate {
	if v != nil {
		_u.SetCaptchaTimes(*v)
	}
	return _u
}

// AddCaptchaTimes adds value to the "captcha_times" field.
func (_u *UserPasswordPolicyUpdate) AddCaptchaTimes(v int32) *UserPasswordPolicyUpdate {
	_u.mutation.AddCaptchaTimes(v)
	return _u
}

// ClearCaptchaTimes clears the value of the "captcha_times" field.
func (_u *UserPasswordPolicyUpdate) ClearCaptchaTimes() *UserPasswordPolicyUpdate {
	_u.mutation.ClearCaptchaTimes()
	return _u
}

// Mutation returns the UserPasswordPolicyMutation object of the builder.
func (_u *UserPasswordPolicyUpdate) Mutation() *UserPasswordPolicyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserPasswordPolicyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserPasswordPolicyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserPasswordPolicyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserPasswordPolicyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserPasswordPolicyUpdate) check() error {
	if v, ok := _u.mutation.Length(); ok {
		if err := userpasswordpolicy.LengthValidator(v); err != nil {
			return &ValidationError{Name: "length", err: fmt.Errorf(`ent: validator failed for field "UserPasswordPolicy.length": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IncludeChar(); ok {
		if err := userpasswordpolicy.IncludeCharValidator(v); err != nil {
			return &ValidationError{Name: "include_char", err: fmt.Errorf(`ent: validator failed for field "UserPasswordPolicy.include_char": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InvalidDay(); ok {
		if err := userpasswordpolicy.InvalidDayValidator(v); err != nil {
			return &ValidationError{Name: "invalid_day", err: fmt.Errorf(`ent: validator failed for field "UserPasswordPolicy.invalid_day": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Retry(); ok {
		if err := userpasswordpolicy.RetryValidator(v); err != nil {
			return &ValidationError{Name: "retry", err: fmt.Errorf(`ent: validator failed for field "UserPasswordPolicy.retry": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CaptchaTimes(); ok {
		if err := userpasswordpolicy.CaptchaTimesValidator(v); err != nil {
			return &ValidationError{Name: "captcha_times", err: fmt.Errorf(`ent: validator failed for field "UserPasswordPolicy.captcha_times": %w`, err)}
		}
	}
	return nil
}

func (_u *UserPasswordPolicyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userpasswordpolicy.Table, userpasswordpolicy.Columns, sqlgraph.NewFieldSpec(userpasswordpolicy.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(userpasswordpolicy.FieldUpdatedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(userpasswordpolicy.FieldUpdatedBy, field.TypeInt, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(userpasswordpolicy.FieldUpdatedBy, field.TypeInt)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userpasswordpolicy.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(userpasswordpolicy.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Length(); ok {
		_spec.SetField(userpasswordpolicy.FieldLength, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedLength(); ok {
		_spec.AddField(userpasswordpolicy.FieldLength, field.TypeInt32, value)
	}
	if _u.mutation.LengthCleared() {
		_spec.ClearField(userpasswordpolicy.FieldLength, field.TypeInt32)
	}
	if value, ok := _u.mutation.IncludeElement(); ok {
		_spec.SetField(userpasswordpolicy.FieldIncludeElement, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedIncludeElement(); ok {
		_spec.AddField(userpasswordpolicy.FieldIncludeElement, field.TypeInt32, value)
	}
	if _u.mutation.IncludeElementCleared() {
		_spec.ClearField(userpasswordpolicy.FieldIncludeElement, field.TypeInt32)
	}
	if value, ok := _u.mutation.IncludeChar(); ok {
		_spec.SetField(userpasswordpolicy.FieldIncludeChar, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedIncludeChar(); ok {
		_spec.AddField(userpasswordpolicy.FieldIncludeChar, field.TypeInt32, value)
	}
	if _u.mutation.IncludeCharCleared() {
		_spec.ClearField(userpasswordpolicy.FieldIncludeChar, field.TypeInt32)
	}
	if value, ok := _u.mutation.AllowIncludeUserName(); ok {
		_spec.SetField(userpasswordpolicy.FieldAllowIncludeUserName, field.TypeBool, value)
	}
	if _u.mutation.AllowIncludeUserNameCleared() {
		_spec.ClearField(userpasswordpolicy.FieldAllowIncludeUserName, field.TypeBool)
	}
	if value, ok := _u.mutation.InvalidDay(); ok {
		_spec.SetField(userpasswordpolicy.FieldInvalidDay, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedInvalidDay(); ok {
		_spec.AddField(userpasswordpolicy.FieldInvalidDay, field.TypeInt32, value)
	}
	if _u.mutation.InvalidDayCleared() {
		_spec.ClearField(userpasswordpolicy.FieldInvalidDay, field.TypeInt32)
	}
	if value, ok := _u.mutation.InvalidLoginLimit(); ok {
		_spec.SetField(userpasswordpolicy.FieldInvalidLoginLimit, field.TypeBool, value)
	}
	if _u.mutation.InvalidLoginLimitCleared() {
		_spec.ClearField(userpasswordpolicy.FieldInvalidLoginLimit, field.TypeBool)
	}
	if value, ok := _u.mutation.Retry(); ok {
		_spec.SetField(userpasswordpolicy.FieldRetry, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedRetry(); ok {
		_spec.AddField(userpasswordpolicy.FieldRetry, field.TypeInt32, value)
	}
	if _u.mutation.RetryCleared() {
		_spec.ClearField(userpasswordpolicy.FieldRetry, field.TypeInt32)
	}
	if value, ok := _u.mutation.CaptchaTimes(); ok {
		_spec.SetField(userpasswordpolicy.FieldCaptchaTimes, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedCaptchaTimes(); ok {
		_spec.AddField(userpasswordpolicy.FieldCaptchaTimes, field.TypeInt32, value)
	}
	if _u.mutation.CaptchaTimesCleared() {
		_spec.ClearField(userpasswordpolicy.FieldCaptchaTimes, field.TypeInt32)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userpasswordpolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserPasswordPolicyUpdateOne is the builder for updating a single UserPasswordPolicy entity.
type UserPasswordPolicyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserPasswordPolicyMutation
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *UserPasswordPolicyUpdateOne) SetUpdatedBy(v int) *UserPasswordPolicyUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *UserPasswordPolicyUpdateOne) SetNillableUpdatedBy(v *int) *UserPasswordPolicyUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *UserPasswordPolicyUpdateOne) AddUpdatedBy(v int) *UserPasswordPolicyUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *UserPasswordPolicyUpdateOne) ClearUpdatedBy() *UserPasswordPolicyUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserPasswordPolicyUpdateOne) SetUpdatedAt(v time.Time) *UserPasswordPolicyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *UserPasswordPolicyUpdateOne) SetNillableUpdatedAt(v *time.Time) *UserPasswordPolicyUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *UserPasswordPolicyUpdateOne) ClearUpdatedAt() *UserPasswordPolicyUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetLength sets the "length" field.
func (_u *UserPasswordPolicyUpdateOne) SetLength(v int32) *UserPasswordPolicyUpdateOne {
	_u.mutation.ResetLength()
	_u.mutation.SetLength(v)
	return _u
}

// SetNillableLength sets the "length" field if the given value is not nil.
func (_u *UserPasswordPolicyUpdateOne) SetNillableLength(v *int32) *UserPasswordPolicyUpdateOne {
	if v != nil {
		_u.SetLength(*v)
	}
	return _u
}

// AddLength adds value to the "length" field.
func (_u *UserPasswordPolicyUpdateOne) AddLength(v int32) *UserPasswordPolicyUpdateOne {
	_u.mutation.AddLength(v)
	return _u
}

// ClearLength clears the value of the "length" field.
func (_u *UserPasswordPolicyUpdateOne) ClearLength() *UserPasswordPolicyUpdateOne {
	_u.mutation.ClearLength()
	return _u
}

// SetIncludeElement sets the "include_element" field.
func (_u *UserPasswordPolicyUpdateOne) SetIncludeElement(v int32) *UserPasswordPolicyUpdateOne {
	_u.mutation.ResetIncludeElement()
	_u.mutation.SetIncludeElement(v)
	return _u
}

// SetNillableIncludeElement sets the "include_element" field if the given value is not nil.
func (_u *UserPasswordPolicyUpdateOne) SetNillableIncludeElement(v *int32) *UserPasswordPolicyUpdateOne {
	if v != nil {
		_u.SetIncludeElement(*v)
	}
	return _u
}

// AddIncludeElement adds value to the "include_element" field.
func (_u *UserPasswordPolicyUpdateOne) AddIncludeElement(v int32) *UserPasswordPolicyUpdateOne {
	_u.mutation.AddIncludeElement(v)
	return _u
}

// ClearIncludeElement clears the value of the "include_element" field.
func (_u *UserPasswordPolicyUpdateOne) ClearIncludeElement() *UserPasswordPolicyUpdateOne {
	_u.mutation.ClearIncludeElement()
	return _u
}

// SetIncludeChar sets the "include_char" field.
func (_u *UserPasswordPolicyUpdateOne) SetIncludeChar(v int32) *UserPasswordPolicyUpdateOne {
	_u.mutation.ResetIncludeChar()
	_u.mutation.SetIncludeChar(v)
	return _u
}

// SetNillableIncludeChar sets the "include_char" field if the given value is not nil.
func (_u *UserPasswordPolicyUpdateOne) SetNillableIncludeChar(v *int32) *UserPasswordPolicyUpdateOne {
	if v != nil {
		_u.SetIncludeChar(*v)
	}
	return _u
}

// AddIncludeChar adds value to the "include_char" field.
func (_u *UserPasswordPolicyUpdateOne) AddIncludeChar(v int32) *UserPasswordPolicyUpdateOne {
	_u.mutation.AddIncludeChar(v)
	return _u
}

// ClearIncludeChar clears the value of the "include_char" field.
func (_u *UserPasswordPolicyUpdateOne) ClearIncludeChar() *UserPasswordPolicyUpdateOne {
	_u.mutation.ClearIncludeChar()
	return _u
}

// SetAllowIncludeUserName sets the "allow_include_user_name" field.
func (_u *UserPasswordPolicyUpdateOne) SetAllowIncludeUserName(v bool) *UserPasswordPolicyUpdateOne {
	_u.mutation.SetAllowIncludeUserName(v)
	return _u
}

// SetNillableAllowIncludeUserName sets the "allow_include_user_name" field if the given value is not nil.
func (_u *UserPasswordPolicyUpdateOne) SetNillableAllowIncludeUserName(v *bool) *UserPasswordPolicyUpdateOne {
	if v != nil {
		_u.SetAllowIncludeUserName(*v)
	}
	return _u
}

// ClearAllowIncludeUserName clears the value of the "allow_include_user_name" field.
func (_u *UserPasswordPolicyUpdateOne) ClearAllowIncludeUserName() *UserPasswordPolicyUpdateOne {
	_u.mutation.ClearAllowIncludeUserName()
	return _u
}

// SetInvalidDay sets the "invalid_day" field.
func (_u *UserPasswordPolicyUpdateOne) SetInvalidDay(v int32) *UserPasswordPolicyUpdateOne {
	_u.mutation.ResetInvalidDay()
	_u.mutation.SetInvalidDay(v)
	return _u
}

// SetNillableInvalidDay sets the "invalid_day" field if the given value is not nil.
func (_u *UserPasswordPolicyUpdateOne) SetNillableInvalidDay(v *int32) *UserPasswordPolicyUpdateOne {
	if v != nil {
		_u.SetInvalidDay(*v)
	}
	return _u
}

// AddInvalidDay adds value to the "invalid_day" field.
func (_u *UserPasswordPolicyUpdateOne) AddInvalidDay(v int32) *UserPasswordPolicyUpdateOne {
	_u.mutation.AddInvalidDay(v)
	return _u
}

// ClearInvalidDay clears the value of the "invalid_day" field.
func (_u *UserPasswordPolicyUpdateOne) ClearInvalidDay() *UserPasswordPolicyUpdateOne {
	_u.mutation.ClearInvalidDay()
	return _u
}

// SetInvalidLoginLimit sets the "invalid_login_limit" field.
func (_u *UserPasswordPolicyUpdateOne) SetInvalidLoginLimit(v bool) *UserPasswordPolicyUpdateOne {
	_u.mutation.SetInvalidLoginLimit(v)
	return _u
}

// SetNillableInvalidLoginLimit sets the "invalid_login_limit" field if the given value is not nil.
func (_u *UserPasswordPolicyUpdateOne) SetNillableInvalidLoginLimit(v *bool) *UserPasswordPolicyUpdateOne {
	if v != nil {
		_u.SetInvalidLoginLimit(*v)
	}
	return _u
}

// ClearInvalidLoginLimit clears the value of the "invalid_login_limit" field.
func (_u *UserPasswordPolicyUpdateOne) ClearInvalidLoginLimit() *UserPasswordPolicyUpdateOne {
	_u.mutation.ClearInvalidLoginLimit()
	return _u
}

// SetRetry sets the "retry" field.
func (_u *UserPasswordPolicyUpdateOne) SetRetry(v int32) *UserPasswordPolicyUpdateOne {
	_u.mutation.ResetRetry()
	_u.mutation.SetRetry(v)
	return _u
}

// SetNillableRetry sets the "retry" field if the given value is not nil.
func (_u *UserPasswordPolicyUpdateOne) SetNillableRetry(v *int32) *UserPasswordPolicyUpdateOne {
	if v != nil {
		_u.SetRetry(*v)
	}
	return _u
}

// AddRetry adds value to the "retry" field.
func (_u *UserPasswordPolicyUpdateOne) AddRetry(v int32) *UserPasswordPolicyUpdateOne {
	_u.mutation.AddRetry(v)
	return _u
}

// ClearRetry clears the value of the "retry" field.
func (_u *UserPasswordPolicyUpdateOne) ClearRetry() *UserPasswordPolicyUpdateOne {
	_u.mutation.ClearRetry()
	return _u
}

// SetCaptchaTimes sets the "captcha_times" field.
func (_u *UserPasswordPolicyUpdateOne) SetCaptchaTimes(v int32) *UserPasswordPolicyUpdateOne {
	_u.mutation.ResetCaptchaTimes()
	_u.mutation.SetCaptchaTimes(v)
	return _u
}

// SetNillableCaptchaTimes sets the "captcha_times" field if the given value is not nil.
func (_u *UserPasswordPolicyUpdateOne) SetNillableCaptchaTimes(v *int32) *UserPasswordPolicyUpdateOne {
	if v != nil {
		_u.SetCaptchaTimes(*v)
	}
	return _u
}

// AddCaptchaTimes adds value to the "captcha_times" field.
func (_u *UserPasswordPolicyUpdateOne) AddCaptchaTimes(v int32) *UserPasswordPolicyUpdateOne {
	_u.mutation.AddCaptchaTimes(v)
	return _u
}

// ClearCaptchaTimes clears the value of the "captcha_times" field.
func (_u *UserPasswordPolicyUpdateOne) ClearCaptchaTimes() *UserPasswordPolicyUpdateOne {
	_u.mutation.ClearCaptchaTimes()
	return _u
}

// Mutation returns the UserPasswordPolicyMutation object of the builder.
func (_u *UserPasswordPolicyUpdateOne) Mutation() *UserPasswordPolicyMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserPasswordPolicyUpdate builder.
func (_u *UserPasswordPolicyUpdateOne) Where(ps ...predicate.UserPasswordPolicy) *UserPasswordPolicyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserPasswordPolicyUpdateOne) Select(field string, fields ...string) *UserPasswordPolicyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserPasswordPolicy entity.
func (_u *UserPasswordPolicyUpdateOne) Save(ctx context.Context) (*UserPasswordPolicy, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserPasswordPolicyUpdateOne) SaveX(ctx context.Context) *UserPasswordPolicy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserPasswordPolicyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserPasswordPolicyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserPasswordPolicyUpdateOne) check() error {
	if v, ok := _u.mutation.Length(); ok {
		if err := userpasswordpolicy.LengthValidator(v); err != nil {
			return &ValidationError{Name: "length", err: fmt.Errorf(`ent: validator failed for field "UserPasswordPolicy.length": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IncludeChar(); ok {
		if err := userpasswordpolicy.IncludeCharValidator(v); err != nil {
			return &ValidationError{Name: "include_char", err: fmt.Errorf(`ent: validator failed for field "UserPasswordPolicy.include_char": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InvalidDay(); ok {
		if err := userpasswordpolicy.InvalidDayValidator(v); err != nil {
			return &ValidationError{Name: "invalid_day", err: fmt.Errorf(`ent: validator failed for field "UserPasswordPolicy.invalid_day": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Retry(); ok {
		if err := userpasswordpolicy.RetryValidator(v); err != nil {
			return &ValidationError{Name: "retry", err: fmt.Errorf(`ent: validator failed for field "UserPasswordPolicy.retry": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CaptchaTimes(); ok {
		if err := userpasswordpolicy.CaptchaTimesValidator(v); err != nil {
			return &ValidationError{Name: "captcha_times", err: fmt.Errorf(`ent: validator failed for field "UserPasswordPolicy.captcha_times": %w`, err)}
		}
	}
	return nil
}

func (_u *UserPasswordPolicyUpdateOne) sqlSave(ctx context.Context) (_node *UserPasswordPolicy, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userpasswordpolicy.Table, userpasswordpolicy.Columns, sqlgraph.NewFieldSpec(userpasswordpolicy.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserPasswordPolicy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userpasswordpolicy.FieldID)
		for _, f := range fields {
			if !userpasswordpolicy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userpasswordpolicy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(userpasswordpolicy.FieldUpdatedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(userpasswordpolicy.FieldUpdatedBy, field.TypeInt, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(userpasswordpolicy.FieldUpdatedBy, field.TypeInt)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userpasswordpolicy.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(userpasswordpolicy.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Length(); ok {
		_spec.SetField(userpasswordpolicy.FieldLength, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedLength(); ok {
		_spec.AddField(userpasswordpolicy.FieldLength, field.TypeInt32, value)
	}
	if _u.mutation.LengthCleared() {
		_spec.ClearField(userpasswordpolicy.FieldLength, field.TypeInt32)
	}
	if value, ok := _u.mutation.IncludeElement(); ok {
		_spec.SetField(userpasswordpolicy.FieldIncludeElement, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedIncludeElement(); ok {
		_spec.AddField(userpasswordpolicy.FieldIncludeElement, field.TypeInt32, value)
	}
	if _u.mutation.IncludeElementCleared() {
		_spec.ClearField(userpasswordpolicy.FieldIncludeElement, field.TypeInt32)
	}
	if value, ok := _u.mutation.IncludeChar(); ok {
		_spec.SetField(userpasswordpolicy.FieldIncludeChar, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedIncludeChar(); ok {
		_spec.AddField(userpasswordpolicy.FieldIncludeChar, field.TypeInt32, value)
	}
	if _u.mutation.IncludeCharCleared() {
		_spec.ClearField(userpasswordpolicy.FieldIncludeChar, field.TypeInt32)
	}
	if value, ok := _u.mutation.AllowIncludeUserName(); ok {
		_spec.SetField(userpasswordpolicy.FieldAllowIncludeUserName, field.TypeBool, value)
	}
	if _u.mutation.AllowIncludeUserNameCleared() {
		_spec.ClearField(userpasswordpolicy.FieldAllowIncludeUserName, field.TypeBool)
	}
	if value, ok := _u.mutation.InvalidDay(); ok {
		_spec.SetField(userpasswordpolicy.FieldInvalidDay, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedInvalidDay(); ok {
		_spec.AddField(userpasswordpolicy.FieldInvalidDay, field.TypeInt32, value)
	}
	if _u.mutation.InvalidDayCleared() {
		_spec.ClearField(userpasswordpolicy.FieldInvalidDay, field.TypeInt32)
	}
	if value, ok := _u.mutation.InvalidLoginLimit(); ok {
		_spec.SetField(userpasswordpolicy.FieldInvalidLoginLimit, field.TypeBool, value)
	}
	if _u.mutation.InvalidLoginLimitCleared() {
		_spec.ClearField(userpasswordpolicy.FieldInvalidLoginLimit, field.TypeBool)
	}
	if value, ok := _u.mutation.Retry(); ok {
		_spec.SetField(userpasswordpolicy.FieldRetry, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedRetry(); ok {
		_spec.AddField(userpasswordpolicy.FieldRetry, field.TypeInt32, value)
	}
	if _u.mutation.RetryCleared() {
		_spec.ClearField(userpasswordpolicy.FieldRetry, field.TypeInt32)
	}
	if value, ok := _u.mutation.CaptchaTimes(); ok {
		_spec.SetField(userpasswordpolicy.FieldCaptchaTimes, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedCaptchaTimes(); ok {
		_spec.AddField(userpasswordpolicy.FieldCaptchaTimes, field.TypeInt32, value)
	}
	if _u.mutation.CaptchaTimesCleared() {
		_spec.ClearField(userpasswordpolicy.FieldCaptchaTimes, field.TypeInt32)
	}
	_node = &UserPasswordPolicy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userpasswordpolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
