namespace: default
appName: file
version: 0.0.1
development: true
# use open telemetry
#otel:
#  traceExporter: otlp
#  otlp:
#    endpoint: "127.0.0.1:4317"
#    client:
#      dialOption:
#        - timeout: 5s

log:
  withTraceID: true
  traceIDKey: "traceId"
  cores:
    - level: debug
      outputPaths:
        - stdout

web:
  server:
    addr: 127.0.0.1:10071
  engine:
    routerGroups:
      - default:
          middlewares:
            - accessLog:
            - recovery:
            - errorHandle:
            - jwt:
                signingMethod: "HS256"
                signingKey: "secret"

store:
  portal:
    driverName: mysql
    dsn: "root:@tcp(localhost:3306)/portal?parseTime=true&loc=Local"

entcache:
  hashQueryTTL: 5s
#  ttl: 5m # level: db时有效

files:
  local:
    baseDir: "tmp"
    endpoint: "http://127.0.0.1:10071"